week39_nahye03
SMU-Algorithm-Study/Algorithm pull request #107
Opened 2022-06-23 09:20 UTC by nahye03

2022-06-26 07:23 UTC, HanNayeoniee commented on week39/소수만들기_nahye03.py
> +def is_prime(num):
- num < 2인 경우에 False를 반환하나요?

2022-06-26 07:39 UTC, HanNayeoniee requested changes

2022-06-26 07:39 UTC, HanNayeoniee commented on week39/소수만들기_nahye03.py
> +    return True
- 모든 약수는 대칭 형태이기 때문에 num 대신 num의 제곱근까지만 나누어 떨어지는지 확인해 소수 여부를 확인할 수 있습니다.
```suggestion
def is_prime(num):
    for i in range(2, int(num*0.5)+1):
        if num % i == 0:
            return False
    return True
```

2022-06-26 07:39 UTC, HanNayeoniee commented on week39/소수만들기_nahye03.py
> +                nums_sum = nums[i]+nums[j]+nums[l]
이 삼중 for문을 아래의 다른 방법처럼 combinations을 사용해 숫자 3개의 조합을 구하고, 위에서 선언한 소수 판별 함수 `is_prime()`을 사용하면 기존 함수랑 다른 방법을 절반씩 섞어서 쓸 수 있을 것 같아요

2022-06-26 07:39 UTC, HanNayeoniee commented on week39/체육복_nahye03.py
> +
set 자료구조를 사용하면 간단하게 구현할 수 있군요! 배워갑니다 ㅎㅎ

2022-06-26 12:10 UTC, nahye03 commented on week39/소수만들기_nahye03.py
> +def is_prime(num):
문제가 1이상의 서로 다른 3개를 더하는 것이여서  최소가 되는 경우가 6이기 때문에 num이 2이하인 경우는 고려하지 않았습니다. 1부터 소수를 판별하는 경우라면 앞에 if문으로 제한을 두는것이 좋을 것 같습니다!

2022-06-26 12:13 UTC, nahye03 commented on week39/소수만들기_nahye03.py
> +                nums_sum = nums[i]+nums[j]+nums[l]
기존의 함수를 알고 있으면 좋은것 같아요!

2022-06-29 14:25 UTC, merged

2022-07-02 06:17 UTC, HanNayeoniee commented on week39/소수만들기_nahye03.py
> +def is_prime(num):
소수 판별 함수에서는 필요하지만, 이 문제의 경우에는 필요하지 않군요! 설명 감사합니당