week40_hyeinlee725
SMU-Algorithm-Study/Algorithm pull request #112
Opened 2022-07-01 15:01 UTC by hyeinlee725

2022-07-02 07:54 UTC, HanNayeoniee requested changes

2022-07-02 07:54 UTC, HanNayeoniee commented on week40/3진법 뒤집기_hyeinlee725.py
> +        n = n // 3 # 몫
`re, n = divmod(n, 3)`을 사용하면 몫이랑 나머지를 한 번에 구할 수 있어요!

2022-07-02 07:54 UTC, HanNayeoniee commented on week40/키패드누르기_hyeinlee725.py
> +              '*':[3, 0], 0: [3, 1], '#': [3, 2]}
저는 `keypad` 딕셔너리의 value 부분을 튜플 (0,0)로 정의했는데, 이 부분만 빼고 제 코드랑 거의 동일하네요!

2022-07-02 07:54 UTC, HanNayeoniee commented on week40/키패드누르기_hyeinlee725.py
> +                right_dis += abs(r - n)
숫자-왼손, 숫자-오른손의 거리를 담는 변수 `left_dis`, `right_dis`를 0으로 따로 초기화하지 않고, 22-23에서 계산한 값으로 바로 초기화해서 사용할 수 있지 않을까요?

2022-07-02 07:54 UTC, HanNayeoniee commented on week40/모의고사_hyeinlee725.py
> +            count3 += 1
오 이렇게 구할 수도 있군요!

2022-07-02 13:46 UTC, nahye03 commented on week40/모의고사_hyeinlee725.py
> +            count3 += 1
이 방법 너무 간단하고 좋은 것 같아요!

2022-07-02 13:50 UTC, nahye03 commented on week40/키패드누르기_hyeinlee725.py
> +                right_dis += abs(r - n)
거리 계산에 zip 사용하는거 좋은것 같아요!!

2022-07-04 08:22 UTC, hyeinlee725 commented on week40/3진법 뒤집기_hyeinlee725.py
> +        n = n // 3 # 몫
오 다음에 할 땐 써봐야겠어요

2022-07-04 08:23 UTC, hyeinlee725 commented on week40/키패드누르기_hyeinlee725.py
> +                right_dis += abs(r - n)
다음에 써볼께요!!

2022-07-04 08:23 UTC, hyeinlee725 commented on week40/키패드누르기_hyeinlee725.py
> +                right_dis += abs(r - n)
오 그렇게 초기화하면 코드가 좀 더 간편해질거 같네요

2022-07-04 12:37 UTC, merged