week41_nahye03
SMU-Algorithm-Study/Algorithm pull request #114
Opened 2022-07-07 15:42 UTC by nahye03

2022-07-10 05:48 UTC, HanNayeoniee requested changes

2022-07-10 05:48 UTC, HanNayeoniee commented on week41/신규 아이디 추천_nahye03.py
> +    return a
먼저 merge 한 것 같아서 코멘트로 리뷰 남길게요!
2단계에서 특수문자 제거할 때 정규표현식 `re` 모듈 사용하면 for문을 사용하지 않고 가능합니다!
```
import re
a = re.sub(r'[^a-z0-9-_.]', '', a)
```
- `a-z` : 알파벳 소문자
- `0-9` : 숫자
- `-_.` : 아이디에 사용할 수 있는 문자 3개
라는 의미이고, `^`를 사용하면 안에 정의한 문자열을 제외한 문자들을 공백으로 치환하는 함수입니다.
반대로, `^`를 빼면 안에 정의한 문자열을 공백으로 치환해주는 함수가 됩니다!

한 가지 궁금한 점이 있는데요, 6단계(28번째 라인)에서는 마지막 문자가 '.'인 경우에만 삭제해야 합니다. `strip()`을 사용하면 문자열 **양끝**의 문자를 삭제하는걸로 아는데요, 이 경우에는 상관이 없을까요?

2022-07-10 06:01 UTC, HanNayeoniee commented on week41/신규 아이디 추천_nahye03.py
> +    return a
이미 4단계에서 맨 앞에 존재하는 '.'를 삭제해서 6단계에서 `strip()`이랑 `rstrip()`의 결과가 같겠네요! 이해했습니닿ㅎ

2022-07-11 04:43 UTC, HanNayeoniee commented on week41/신규 아이디 추천_nahye03.py
> +    return a
[토닥토닥 파이썬](https://wikidocs.net/80567) 여기에 정규표현식에 대해 잘 나와있습니다~

2022-07-12 06:28 UTC, nahye03 commented on week41/신규 아이디 추천_nahye03.py
> +    return a
re 모듈 제대로 배워가네요!! 감사합니다ㅎㅎ

2022-07-12 06:29 UTC, merged